### ISSUE TITLE
TypeError:

### ISSUE THREAD

**Issue by hellojialee** [Bingohong/GroupNormalization-tensorflow#2]
TypeError: Failed to convert object of type <class 'tuple'> to Tensor. Contents: (-1, 32, 2, None, None). Consider casting elements to a supported type.

When I replace the BN with the customized GN, I met this error. How can I solve it? Thank you!

**Comment by YJHMITWEB** [comment]
Have you solve it?

**Comment by YJHMITWEB** [comment]
@USTClj Have you solved it?

**Comment by ConradSun** [comment]
Hi, have you solved this problem? I met the same.
